services:
  gateway:
    build: ../../gateway
    restart: always
    ports:
      - "127.0.0.1:8000:8000"
    command: gateway run --config /etc/gateway/config.json
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
    volumes:
      - ./config.json:/etc/gateway/config.json:ro
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
